name: Build & Push Prod
on:
  push:
    branches:
        - main
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build api images
      run: |
        cd api
        docker build -t zme-api -f ZME.API/Dockerfile .
    - name: Build ui image
      run: |
        cd ui
        docker build -t zme-ui .
    - name: Tag images
      run: |
        docker tag zme-api ghcr.io/Memphis-ARTCC/zme-api:latest
        docker tag zme-ui ghcr.io/Memphis-ARTCC/zme-ui:latest
    - name: Push images
      run: |
        docker push ghcr.io/Memphis-ARTCC/zme-api:latest
        docker push ghcr.io/Memphis-ARTCC/zme-ui:latest
    # - name: Restart api
    #   uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     args: -n zme-prod rollout restart deployment api-prod
    # - name: Restart ui
    #   uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     args: -n zme-prod rollout restart deployment ui-prod