name: Build
on:
  pull_request:
    types: [opened, reopened]
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Build api images
      run: |
        cd api
        docker build -t zme-api -f ZME.API/Dockerfile .
    - name: Build ui image
      run: |
        cd ui
        docker build -t zme-ui .